on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/73d6dc20ff49b763c80988b5ff3ab7ba
          gist_title: 6-ADCSetPoint-MPLAB-4550.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F4550/6_Set_Point.X/main.c
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/01b85b31d93412b6a1d5690511f5e1b1
          gist_title: 6-ADCSetPoint-MPLAB.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F45K50/6_ADC_SetPoint.X/main.c
          file_encoding: ISO-8859-1